server:
  port: 8031

security.basic.enabled: false

turbine:
  aggregator:
    clusterConfig: default
  appConfig: loginservice
  clusterNameExpression: new String('default')
eureka:
  client:
    serviceUrl:
      defaultZone:  http://discovery1:8761/eureka/,http://discovery2:8762/eureka/



